name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable
    - run: wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
    - run: unzip chromedriver_linux64.zip
    - run: sudo mv chromedriver /usr/bin/chromedriver
    - run: sudo chown root:root /usr/bin/chromedriver
    - run: sudo chmod +x /usr/bin/chromedriver
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: node index.js
